// -----------------------------------------------------------------------------
﻿//
﻿// Copyright Microsoft Corporation
﻿// Licensed under the Apache License, Version 2.0 (the "License");
﻿// you may not use this file except in compliance with the License.
﻿// You may obtain a copy of the License at
﻿// http://www.apache.org/licenses/LICENSE-2.0
﻿// Unless required by applicable law or agreed to in writing, software
﻿// distributed under the License is distributed on an "AS IS" BASIS,
﻿// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
﻿// See the License for the specific language governing permissions and
﻿// limitations under the License.
﻿// -----------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.Commands.Batch.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using Azure.Batch;
    
    
    public partial class PSAutoPoolSpecification
    {
        
        internal AutoPoolSpecification omObject;
        
        private PSPoolSpecification poolSpecification;
        
        public PSAutoPoolSpecification()
        {
            omObject = new AutoPoolSpecification();
        }
        
        internal PSAutoPoolSpecification(AutoPoolSpecification omObject)
        {
            if (omObject == null)
            {
                throw new ArgumentNullException("omObject");
            }
            this.omObject = omObject;
        }
        
        public string AutoPoolIdPrefix
        {
            get
            {
                return omObject.AutoPoolIdPrefix;
            }
            set
            {
                omObject.AutoPoolIdPrefix = value;
            }
        }
        
        public Boolean? KeepAlive
        {
            get
            {
                return omObject.KeepAlive;
            }
            set
            {
                omObject.KeepAlive = value;
            }
        }
        
        public Azure.Batch.Common.PoolLifetimeOption PoolLifetimeOption
        {
            get
            {
                return omObject.PoolLifetimeOption;
            }
            set
            {
                omObject.PoolLifetimeOption = value;
            }
        }
        
        public PSPoolSpecification PoolSpecification
        {
            get
            {
                if (poolSpecification == null 
                    && omObject.PoolSpecification != null)
                {
                    poolSpecification = new PSPoolSpecification(omObject.PoolSpecification);
                }
                return poolSpecification;
            }
            set
            {
                if (value == null)
                {
                    omObject.PoolSpecification = null;
                }
                else
                {
                    omObject.PoolSpecification = value.omObject;
                }
                poolSpecification = value;
            }
        }
    }
}
