// -----------------------------------------------------------------------------
﻿//
﻿// Copyright Microsoft Corporation
﻿// Licensed under the Apache License, Version 2.0 (the "License");
﻿// you may not use this file except in compliance with the License.
﻿// You may obtain a copy of the License at
﻿// http://www.apache.org/licenses/LICENSE-2.0
﻿// Unless required by applicable law or agreed to in writing, software
﻿// distributed under the License is distributed on an "AS IS" BASIS,
﻿// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
﻿// See the License for the specific language governing permissions and
﻿// limitations under the License.
﻿// -----------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.Commands.Batch.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using Azure.Batch;
    
    
    public partial class PSCertificateReference
    {
        
        internal CertificateReference omObject;
        
        public PSCertificateReference()
        {
            omObject = new CertificateReference();
        }
        
        public PSCertificateReference(PSCertificate baseCertificate)
        {
            omObject = new CertificateReference(baseCertificate.omObject);
        }
        
        internal PSCertificateReference(CertificateReference omObject)
        {
            if (omObject == null)
            {
                throw new ArgumentNullException("omObject");
            }
            this.omObject = omObject;
        }
        
        public Azure.Batch.Common.CertStoreLocation? StoreLocation
        {
            get
            {
                return omObject.StoreLocation;
            }
            set
            {
                omObject.StoreLocation = value;
            }
        }
        
        public string StoreName
        {
            get
            {
                return omObject.StoreName;
            }
            set
            {
                omObject.StoreName = value;
            }
        }
        
        public string Thumbprint
        {
            get
            {
                return omObject.Thumbprint;
            }
            set
            {
                omObject.Thumbprint = value;
            }
        }
        
        public string ThumbprintAlgorithm
        {
            get
            {
                return omObject.ThumbprintAlgorithm;
            }
            set
            {
                omObject.ThumbprintAlgorithm = value;
            }
        }
        
        public Azure.Batch.Common.CertificateVisibility? Visibility
        {
            get
            {
                return omObject.Visibility;
            }
            set
            {
                omObject.Visibility = value;
            }
        }
    }
}
