// -----------------------------------------------------------------------------
﻿//
﻿// Copyright Microsoft Corporation
﻿// Licensed under the Apache License, Version 2.0 (the "License");
﻿// you may not use this file except in compliance with the License.
﻿// You may obtain a copy of the License at
﻿// http://www.apache.org/licenses/LICENSE-2.0
﻿// Unless required by applicable law or agreed to in writing, software
﻿// distributed under the License is distributed on an "AS IS" BASIS,
﻿// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
﻿// See the License for the specific language governing permissions and
﻿// limitations under the License.
﻿// -----------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.Commands.Batch.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using Azure.Batch;
    
    
    public partial class PSCloudJobSchedule
    {
        
        internal CloudJobSchedule omObject;
        
        private PSJobScheduleExecutionInformation executionInformation;
        
        private PSJobSpecification jobSpecification;
        
        private IList<PSMetadataItem> metadata;
        
        private PSSchedule schedule;
        
        private PSJobScheduleStatistics statistics;
        
        internal PSCloudJobSchedule(CloudJobSchedule omObject)
        {
            if (omObject == null)
            {
                throw new ArgumentNullException("omObject");
            }
            this.omObject = omObject;
        }
        
        public DateTime? CreationTime
        {
            get
            {
                return omObject.CreationTime;
            }
        }
        
        public string DisplayName
        {
            get
            {
                return omObject.DisplayName;
            }
            set
            {
                omObject.DisplayName = value;
            }
        }
        
        public string ETag
        {
            get
            {
                return omObject.ETag;
            }
        }
        
        public PSJobScheduleExecutionInformation ExecutionInformation
        {
            get
            {
                if (executionInformation == null 
                    && omObject.ExecutionInformation != null)
                {
                    executionInformation = new PSJobScheduleExecutionInformation(omObject.ExecutionInformation);
                }
                return executionInformation;
            }
        }
        
        public string Id
        {
            get
            {
                return omObject.Id;
            }
            set
            {
                omObject.Id = value;
            }
        }
        
        public PSJobSpecification JobSpecification
        {
            get
            {
                if (jobSpecification == null 
                    && omObject.JobSpecification != null)
                {
                    jobSpecification = new PSJobSpecification(omObject.JobSpecification);
                }
                return jobSpecification;
            }
            set
            {
                if (value == null)
                {
                    omObject.JobSpecification = null;
                }
                else
                {
                    omObject.JobSpecification = value.omObject;
                }
                jobSpecification = value;
            }
        }
        
        public DateTime? LastModified
        {
            get
            {
                return omObject.LastModified;
            }
        }
        
        public IList<PSMetadataItem> Metadata
        {
            get
            {
                if (metadata == null 
                    && omObject.Metadata != null)
                {
                    List<PSMetadataItem> list;
                    list = new List<PSMetadataItem>();
                    IEnumerator<MetadataItem> enumerator;
                    enumerator = omObject.Metadata.GetEnumerator();
                    for (
                    ; enumerator.MoveNext(); 
                    )
                    {
                        list.Add(new PSMetadataItem(enumerator.Current));
                    }
                    metadata = list;
                }
                return metadata;
            }
            set
            {
                if (value == null)
                {
                    omObject.Metadata = null;
                }
                else
                {
                    omObject.Metadata = new List<MetadataItem>();
                }
                metadata = value;
            }
        }
        
        public Azure.Batch.Common.JobScheduleState? PreviousState
        {
            get
            {
                return omObject.PreviousState;
            }
        }
        
        public DateTime? PreviousStateTransitionTime
        {
            get
            {
                return omObject.PreviousStateTransitionTime;
            }
        }
        
        public PSSchedule Schedule
        {
            get
            {
                if (schedule == null 
                    && omObject.Schedule != null)
                {
                    schedule = new PSSchedule(omObject.Schedule);
                }
                return schedule;
            }
            set
            {
                if (value == null)
                {
                    omObject.Schedule = null;
                }
                else
                {
                    omObject.Schedule = value.omObject;
                }
                schedule = value;
            }
        }
        
        public Azure.Batch.Common.JobScheduleState? State
        {
            get
            {
                return omObject.State;
            }
        }
        
        public DateTime? StateTransitionTime
        {
            get
            {
                return omObject.StateTransitionTime;
            }
        }
        
        public PSJobScheduleStatistics Statistics
        {
            get
            {
                if (statistics == null 
                    && omObject.Statistics != null)
                {
                    statistics = new PSJobScheduleStatistics(omObject.Statistics);
                }
                return statistics;
            }
        }
        
        public string Url
        {
            get
            {
                return omObject.Url;
            }
        }
    }
}
