// -----------------------------------------------------------------------------
﻿//
﻿// Copyright Microsoft Corporation
﻿// Licensed under the Apache License, Version 2.0 (the "License");
﻿// you may not use this file except in compliance with the License.
﻿// You may obtain a copy of the License at
﻿// http://www.apache.org/licenses/LICENSE-2.0
﻿// Unless required by applicable law or agreed to in writing, software
﻿// distributed under the License is distributed on an "AS IS" BASIS,
﻿// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
﻿// See the License for the specific language governing permissions and
﻿// limitations under the License.
﻿// -----------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.Commands.Batch.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using Azure.Batch;
    
    
    public partial class PSPoolStatistics
    {
        
        internal PoolStatistics omObject;
        
        private PSResourceStatistics resourceStatistics;
        
        private PSUsageStatistics usageStatistics;
        
        internal PSPoolStatistics(PoolStatistics omObject)
        {
            if (omObject == null)
            {
                throw new ArgumentNullException("omObject");
            }
            this.omObject = omObject;
        }
        
        public DateTime LastUpdateTime
        {
            get
            {
                return omObject.LastUpdateTime;
            }
        }
        
        public PSResourceStatistics ResourceStatistics
        {
            get
            {
                if (resourceStatistics == null 
                    && omObject.ResourceStatistics != null)
                {
                    resourceStatistics = new PSResourceStatistics(omObject.ResourceStatistics);
                }
                return resourceStatistics;
            }
        }
        
        public DateTime StartTime
        {
            get
            {
                return omObject.StartTime;
            }
        }
        
        public string Url
        {
            get
            {
                return omObject.Url;
            }
        }
        
        public PSUsageStatistics UsageStatistics
        {
            get
            {
                if (usageStatistics == null 
                    && omObject.UsageStatistics != null)
                {
                    usageStatistics = new PSUsageStatistics(omObject.UsageStatistics);
                }
                return usageStatistics;
            }
        }
    }
}
