// -----------------------------------------------------------------------------
﻿//
﻿// Copyright Microsoft Corporation
﻿// Licensed under the Apache License, Version 2.0 (the "License");
﻿// you may not use this file except in compliance with the License.
﻿// You may obtain a copy of the License at
﻿// http://www.apache.org/licenses/LICENSE-2.0
﻿// Unless required by applicable law or agreed to in writing, software
﻿// distributed under the License is distributed on an "AS IS" BASIS,
﻿// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
﻿// See the License for the specific language governing permissions and
﻿// limitations under the License.
﻿// -----------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.Commands.Batch.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using Azure.Batch;
    
    
    public partial class PSTaskDependencies
    {
        
        internal TaskDependencies omObject;
        
        private IReadOnlyList<PSTaskIdRange> taskIdRanges;
        
        private IReadOnlyList<String> taskIds;
        
        public PSTaskDependencies(IEnumerable<string> taskIds, IEnumerable<TaskIdRange> taskIdRanges)
        {
            omObject = new TaskDependencies(taskIds, taskIdRanges);
        }
        
        internal PSTaskDependencies(TaskDependencies omObject)
        {
            if (omObject == null)
            {
                throw new ArgumentNullException("omObject");
            }
            this.omObject = omObject;
        }
        
        public IReadOnlyList<PSTaskIdRange> TaskIdRanges
        {
            get
            {
                if (taskIdRanges == null 
                    && omObject.TaskIdRanges != null)
                {
                    List<PSTaskIdRange> list;
                    list = new List<PSTaskIdRange>();
                    IEnumerator<TaskIdRange> enumerator;
                    enumerator = omObject.TaskIdRanges.GetEnumerator();
                    for (
                    ; enumerator.MoveNext(); 
                    )
                    {
                        list.Add(new PSTaskIdRange(enumerator.Current));
                    }
                    taskIdRanges = list.AsReadOnly();
                }
                return taskIdRanges;
            }
        }
        
        public IReadOnlyList<String> TaskIds
        {
            get
            {
                if (taskIds == null 
                    && omObject.TaskIds != null)
                {
                    List<String> list;
                    list = new List<String>();
                    IEnumerator<String> enumerator;
                    enumerator = omObject.TaskIds.GetEnumerator();
                    for (
                    ; enumerator.MoveNext(); 
                    )
                    {
                        list.Add(enumerator.Current);
                    }
                    taskIds = list.AsReadOnly();
                }
                return taskIds;
            }
        }
    }
}
