// ----------------------------------------------------------------------------------
//
// Copyright Microsoft Corporation
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ----------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace Microsoft.Azure.ServiceManagement.Common.XmlSchema
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class PublishData
    {

        private PublishDataPublishProfile[] itemsField;

        /// <remarks/>
        [XmlElement("PublishProfile", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PublishDataPublishProfile[] Items
        {
            get
            {
                return itemsField;
            }
            set
            {
                itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class PublishDataPublishProfile
    {

        private PublishDataPublishProfileSubscription[] subscriptionField;

        private string publishMethodField;

        private string urlField;

        private string managementCertificateField;

        private string SchemaVersionField;

        /// <remarks/>
        [XmlElement("Subscription", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PublishDataPublishProfileSubscription[] Subscription
        {
            get
            {
                return subscriptionField;
            }
            set
            {
                subscriptionField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string PublishMethod
        {
            get
            {
                return publishMethodField;
            }
            set
            {
                publishMethodField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string Url
        {
            get
            {
                return urlField;
            }
            set
            {
                urlField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string ManagementCertificate
        {
            get
            {
                return managementCertificateField;
            }
            set
            {
                managementCertificateField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string SchemaVersion
        {
            get
            {
                return SchemaVersionField;
            }
            set
            {
                SchemaVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class PublishDataPublishProfileSubscription
    {

        private string idField;

        private string nameField;

        private string serviceManagementUrlField;

        private string managementCertificateField;

        /// <remarks/>
        [XmlAttribute]
        public string Id
        {
            get
            {
                return idField;
            }
            set
            {
                idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string Name
        {
            get
            {
                return nameField;
            }
            set
            {
                nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string ServiceManagementUrl
        {
            get
            {
                return serviceManagementUrlField;
            }
            set
            {
                serviceManagementUrlField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string ManagementCertificate
        {
            get
            {
                return managementCertificateField;
            }
            set
            {
                managementCertificateField = value;
            }
        }
    }
}